import Head from 'next/head'
import Link from 'next/link'
import styles from './layout.module.css'

export default function Layout({children, isHome}) {
    return (
        <div className={styles.container}>
            <Head>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {!isHome && (
                <div className={styles.backToHome}>
                    <h2><Link href="/">&larr; Back Home</Link></h2>
                </div>
            )}
            <main>
                {children}
            </main>
        </div>
    ) 
}